// bleTypes.ts (GENERATED FILE - DO NOT EDIT)

export namespace Communication {
  export enum BLE_COMMANDS {
    GET_SD_FILESYSTEM = 0,
    GET_SD_FILE = 1,
    SET_SD_FILE = 2,
    UPDATE_SYSTEM = 3,
    SEND_SMARTFLOOR_DATA = 4,
    SET_WLAN_CREDENTIALS = 5,
    GET_WLAN_NETWORKS = 6,
    GET_WLAN_DATA = 7,
    RESET_USER_DATA = 8,
    SEND_WIFI_DATA = 9,
    SET_LED_COLOR = 10,
    FIRMWARE_UPDATE = 11,
    SET_VOLTAGE_PORT = 12,
    LOG_DATA = 13,
    ERROR_MESSAGE = 255,
  }

}
